### PR TITLE
feat: add ignoreList to discovery

### PR DESCRIPTION
**Pull request by pwilms**
Allow users to ignore devices by name that won't be accessible for alexa.

### CODE REVIEW

**Comment by NorthernMan54** [comment]
Tks for adding this feature, let me check it out and let you know how it goes.  A lot of users keep requesting this but it has never been a priority for me

You should also add yourself to the Credits at the bottom of the README.

**Comment by pwilms** [comment]
@NorthernMan54 I'll push a change that will add switch to specify if the list is to be ignore or the devices on the list will be accepted.￼ I'll have so many devices on my ignore list that it's easier to handle a positive list. 

The other advantage is that new devices aren't exposed to Alexa immediately. That's also a security feature not to expose something accidentally. 

```suggestion
-ignoreList
+deviceHandling:allow|deny
+deviceList:[]
```

The list is only applied when at least one device is given.

**Comment by NorthernMan54** [comment]
Thinking about this further, would it make more sense to use a regular expression rather than a direct match and include 'manufacturer name' in the filter?

And for regular expression, I'm referring to the match function ?  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match

**Comment by pwilms** [comment]
Regex would work but the question is if this is usable for endusers. 

I've posted here also a feature request for better configuration within the UI.

Maybe I'll add "allow", "deny" , "regex" in the handling configuration. Than could a user choose what he want's to use.

**Comment by NorthernMan54** [comment]
Regex doesn't need to be a unique function as the full name of a device is also a valid regex expression.   And have the Easter egg of regex for advanced users.

**Comment by pwilms** [comment]
I've forgotten to push :) here you go with regex.

**Comment by NorthernMan54** [comment]
Tks @pwilms, this enhancement has had a lot of demand over the years and this resolves all these old issues. #362 #342 #313 #290 #275 #90 #80

**Comment by NorthernMan54** [comment]
Published as version v0.5.14

**Comment by jacesaces** [comment]
Is there a readme for this feature?  I'd love to use the 'Accept Devices' concept and be able to declare which specific devices within homebridge to expose to Alexa.  

It seems for this: 'How to handle devices in the deviceList' I'd say "allow".  But then for this section 'Devices to be allowed or denied', I'm not sure what the syntax should look like and how to specify the devices (I'm basically only going to be exposing the dummy sensors configured in NorthernMan's other plugin for dummy switches).  Any insight you can share?

**Comment by kolorfilm** [comment]
> Is there a readme for this feature?  I'd love to use the 'Accept Devices' concept and be able to declare which specific devices within homebridge to expose to Alexa.  
> 
> 
> 
> It seems for this: 'How to handle devices in the deviceList' I'd say "allow".  But then for this section 'Devices to be allowed or denied', I'm not sure what the syntax should look like and how to specify the devices (I'm basically only going to be exposing the dummy sensors configured in NorthernMan's other plugin for dummy switches).  Any insight you can share?

Would be very helpful.

**Pull request merged**
